# Generated by Django 6.0.2 on 2026-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
